name: docker hub CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t linear_model .
      - name: Tags
        run: |
          docker tag linear_model ${{ secrets.DOCKER_USER }}/linear_model:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/linear_model:latest
